const state={user:null,status:null,users:[],authMode:'login'};
const $=id=>document.getElementById(id);
function fullEmail(input){const v=input.value.trim();return v.includes('@')?v:v+'@qq.com'}
async function request(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options});const data=await response.json();if(!response.ok)throw new Error(data.message||'请求失败');return data}
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',2600)}
function avatar(el,user){el.textContent=(user?.username||'?').slice(0,1).toUpperCase();el.classList.toggle('has-image',!!user?.avatarUrl);el.style.backgroundImage=user?.avatarUrl?`url(${user.avatarUrl}?v=${Date.now()})`:''}
function updateAccount(){const logged=!!state.user;$('authButton').classList.toggle('hidden',logged);$('profileButton').classList.toggle('hidden',!logged);document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',!state.user?.isAdmin));if(logged){$('navUsername').textContent=state.user.username;avatar($('navAvatar'),state.user);$('profileUsername').textContent=state.user.username;$('profileRole').textContent=state.user.isAdmin?'社区管理员':'社区成员';avatar($('profileAvatar'),state.user)}$('joinButton').textContent=logged?'查看个人资料':'创建账户'}
async function loadMe(){const data=await request('/api/community/me');state.user=data.user;updateAccount();if(state.user?.isAdmin)loadAdmin()}
async function loadStatus(){const data=await request('/api/community/status');state.status=data;$('serverName').textContent=data.serverName;$('serverMotd').textContent=data.motd;const roomState=data.roomState;$('onlineCount').textContent=roomState.onlinePlayers;$('roomCount').textContent=roomState.activeRooms;$('gameCount').textContent=roomState.runningGames;renderRooms(roomState.rooms)}
function renderRooms(rooms){const grid=$('roomsGrid');grid.innerHTML='';$('roomsEmpty').classList.toggle('hidden',rooms.length>0);rooms.forEach(room=>{const el=document.createElement('article');el.className='room';const playerDots=room.players.slice(0,5).map(p=>`<span class="player-dot" title="${escapeHtml(p.username)}">${escapeHtml(p.username.slice(0,1).toUpperCase())}</span>`).join('');el.innerHTML=`<div class="room-top"><span class="room-id">ROOM ${String(room.id).padStart(3,'0')}</span><span class="room-state">${room.gameRunning?'游戏中':'等待中'}</span></div><h3>${escapeHtml(room.songName)}</h3><div class="players">${playerDots}</div><div class="room-meta"><span>${escapeHtml(room.owner)} 的房间</span><span>${room.playerCount} 人</span></div>`;grid.appendChild(el)})}
function escapeHtml(value){const el=document.createElement('div');el.textContent=value??'';return el.innerHTML}
function openAuth(mode='login'){$('authDialog').showModal();setAuthMode(mode)}
function setAuthMode(mode){state.authMode=mode;document.querySelectorAll('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('authTitle').textContent=mode==='login'?'登录社区':'创建社区账户';$('authHint').textContent=mode==='login'?'使用社区账户登录。':'用户名 3-24 位，密码至少 8 位，邮箱仅支持 @qq.com。';$('passwordInput').autocomplete=mode==='login'?'current-password':'new-password';const ef=$('emailField'),ei=$('emailInput'),ec=$('emailCodeInput'),fl=$('forgotLink');if(ef)ef.classList.toggle('hidden',mode!=='register');if(ei)ei.required=mode==='register';if(ec)ec.required=mode==='register';if(fl)fl.classList.toggle('hidden',mode!=='login')}
async function submitAuth(event){event.preventDefault();try{const payload={username:$('usernameInput').value.trim(),password:$('passwordInput').value};if(state.authMode==='register'){payload.email=fullEmail($('emailInput'));payload.code=$('emailCodeInput').value.trim()}const data=await request(`/api/community/${state.authMode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.user=data.user;const dialog=$('authDialog');if(dialog.open)dialog.close();event.target.reset();updateAccount();toast(state.authMode==='login'?'登录成功':'注册成功');if(state.user.isAdmin)loadAdmin()}catch(error){toast(error.message,true)}}
async function logout(){await request('/api/community/logout',{method:'POST'});state.user=null;updateAccount();$('profileDialog').close();showView('community');toast('已退出登录')}
async function uploadAvatar(event){const file=event.target.files[0];if(!file)return;try{const data=await request('/api/community/avatar',{method:'POST',headers:{'Content-Type':file.type},body:file});state.user.avatarUrl=data.avatarUrl;updateAccount();toast('头像已更新')}catch(error){toast(error.message,true)}event.target.value=''}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='admin')loadAdmin();if(name==='announcements')loadAnnouncements()}
async function loadAnnouncements(){try{const data=await request('/api/community/announcements');renderAnnouncements(data.announcements)}catch(error){toast(error.message,true)}}
const announcementTypeName={maintenance:'维护公告',update:'更新公告',other:'其他公告'};
function renderAnnouncements(list){const root=$('announcementsList');root.innerHTML='';$('announcementsEmpty').classList.toggle('hidden',list.length>0);list.forEach(item=>{const el=document.createElement('article');el.className='announcement';el.innerHTML=`<div class="announcement-head"><span class="badge type-${escapeHtml(item.type)}">${announcementTypeName[item.type]||'其他公告'}</span><time>${new Date(item.publishedAt).toLocaleString('zh-CN')}</time></div><h3>${escapeHtml(item.title)}</h3><div class="announcement-content">${escapeHtml(item.content).replace(/\n/g,'<br>')}</div>`;root.appendChild(el)})}
async function sendCode(button,emailInput){const email=fullEmail(emailInput);if(!email){toast('请先填写 QQ 邮箱',true);return}button.disabled=true;const original=button.textContent;button.textContent='发送中...';try{await request('/api/community/send-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:email})});toast('验证码已发送到邮箱');let count=60;button.textContent=`${count}s 后重发`;const timer=setInterval(()=>{count--;if(count<=0){clearInterval(timer);button.disabled=false;button.textContent='发送验证码'}else button.textContent=`${count}s 后重发`},1000)}catch(error){button.disabled=false;button.textContent=original;toast(error.message,true)}}
async function submitReset(event){event.preventDefault();try{const email=fullEmail($('resetEmailInput'));await request('/api/community/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code:$('resetCodeInput').value.trim(),newPassword:$('resetPasswordInput').value})});$('resetDialog').close();event.target.reset();toast('密码已重置，请重新登录');openAuth('login')}catch(error){toast(error.message,true)}}
async function loadAdmin(){if(!state.user?.isAdmin)return;try{const [users,rooms]=await Promise.all([request('/api/community/admin/users'),request('/api/community/admin/rooms')]);state.users=users.users;$('memberCount').textContent=state.users.length;renderUsers();renderAdminRooms(rooms.rooms)}catch(error){toast(error.message,true)}}
function renderUsers(){const query=$('userSearch').value.trim().toLowerCase();const body=$('userTable');body.innerHTML='';state.users.filter(u=>u.username.toLowerCase().includes(query)).forEach(user=>{const row=document.createElement('tr');row.innerHTML=`<td><span class="user-cell"><span class="avatar small">${escapeHtml(user.username.slice(0,1).toUpperCase())}</span>${escapeHtml(user.username)}</span></td><td><span class="badge">${user.isAdmin?'管理员':'成员'}</span></td><td>${user.banned?'<span class="badge banned">已封禁</span>':'正常'}</td><td>${user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():'从未'}</td><td>${user.isAdmin?'--':`<span class="action-row"><button data-ban="${escapeHtml(user.username)}" data-value="${!user.banned}">${user.banned?'解封':'封禁'}</button><button class="danger-text" data-delete="${escapeHtml(user.username)}">删除</button></span>`}</td>`;body.appendChild(row)})}
function renderAdminRooms(rooms){const root=$('adminRooms');root.innerHTML=rooms.length?'':'<div class="empty-state"><strong>暂无房间</strong></div>';rooms.forEach(room=>{const el=document.createElement('div');el.className='admin-room';el.innerHTML=`<strong>#${room.id} · ${escapeHtml(room.owner)}</strong><span>${room.gameRunning?'游戏中':'等待中'} · ${room.playerCount} 人 · ${escapeHtml(room.songName)}</span><span>${room.players.map(p=>escapeHtml(p.username)).join('、')}</span>`;root.appendChild(el)})}
async function userAction(url,payload){try{const result=await request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});toast(result.message);loadAdmin()}catch(error){toast(error.message,true)}}
async function createUser(event){event.preventDefault();try{const result=await request('/api/community/admin/create-user',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('newUsername').value.trim(),password:$('newPassword').value,email:$('newEmail').value.trim()})});toast(result.message);event.target.reset();loadAdmin()}catch(error){toast(error.message,true)}}
async function publishAnnouncement(event){event.preventDefault();try{const result=await request('/api/community/admin/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:$('announcementType').value,title:$('announcementTitle').value.trim(),content:$('announcementContent').value.trim()})});toast(result.message);event.target.reset();loadAnnouncements()}catch(error){toast(error.message,true)}}
document.addEventListener('click',event=>{const tab=event.target.closest('[data-view]');if(tab)showView(tab.dataset.view);const close=event.target.closest('[data-close]');if(close)$(close.dataset.close).close();const ban=event.target.closest('[data-ban]');if(ban)userAction('/api/community/admin/ban',{username:ban.dataset.ban,banned:ban.dataset.value==='true'});const del=event.target.closest('[data-delete]');if(del&&confirm(`确定删除 ${del.dataset.delete}？`))userAction('/api/community/admin/delete',{username:del.dataset.delete,banned:false})});
$('authButton').addEventListener('click',()=>openAuth('login'));$('joinButton').addEventListener('click',()=>state.user?$('profileDialog').showModal():openAuth('register'));$('profileButton').addEventListener('click',()=>$('profileDialog').showModal());document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));$('authForm').addEventListener('submit',submitAuth);$('logoutButton').addEventListener('click',logout);$('avatarInput').addEventListener('change',uploadAvatar);$('refreshRooms').addEventListener('click',loadStatus);$('refreshAdmin').addEventListener('click',loadAdmin);$('refreshAnnouncements').addEventListener('click',loadAnnouncements);$('userSearch').addEventListener('input',renderUsers);$('sendCodeButton').addEventListener('click',()=>sendCode($('sendCodeButton'),$('emailInput')));$('sendResetCodeButton').addEventListener('click',()=>sendCode($('sendResetCodeButton'),$('resetEmailInput')));$('forgotLink').addEventListener('click',()=>{$('authDialog').close();$('resetDialog').showModal()});$('resetForm').addEventListener('submit',submitReset);$('createUserForm').addEventListener('submit',createUser);$('announcementForm').addEventListener('submit',publishAnnouncement);
Promise.all([loadMe(),loadStatus(),loadAnnouncements()]).catch(error=>toast(error.message,true));setInterval(loadStatus,10000);